// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"workspace-goshow-mall/adaptor/repo/model"
)

func newGoodsCatalogDetail(db *gorm.DB, opts ...gen.DOOption) goodsCatalogDetail {
	_goodsCatalogDetail := goodsCatalogDetail{}

	_goodsCatalogDetail.goodsCatalogDetailDo.UseDB(db, opts...)
	_goodsCatalogDetail.goodsCatalogDetailDo.UseModel(&model.GoodsCatalogDetail{})

	tableName := _goodsCatalogDetail.goodsCatalogDetailDo.TableName()
	_goodsCatalogDetail.ALL = field.NewAsterisk(tableName)
	_goodsCatalogDetail.ID = field.NewInt64(tableName, "id")
	_goodsCatalogDetail.GoodsID = field.NewInt64(tableName, "goods_id")
	_goodsCatalogDetail.CatalogID = field.NewInt64(tableName, "catalog_id")
	_goodsCatalogDetail.Name = field.NewString(tableName, "name")
	_goodsCatalogDetail.IsTrial = field.NewInt32(tableName, "is_trial")
	_goodsCatalogDetail.Status = field.NewInt32(tableName, "status")
	_goodsCatalogDetail.Cover = field.NewString(tableName, "cover")
	_goodsCatalogDetail.Detail = field.NewString(tableName, "detail")
	_goodsCatalogDetail.Homework = field.NewString(tableName, "homework")
	_goodsCatalogDetail.Sort = field.NewInt64(tableName, "sort")
	_goodsCatalogDetail.UpdateAt = field.NewTime(tableName, "update_at")
	_goodsCatalogDetail.UpdateBy = field.NewInt64(tableName, "update_by")

	_goodsCatalogDetail.fillFieldMap()

	return _goodsCatalogDetail
}

// goodsCatalogDetail 商品目录详情表
type goodsCatalogDetail struct {
	goodsCatalogDetailDo goodsCatalogDetailDo

	ALL       field.Asterisk
	ID        field.Int64
	GoodsID   field.Int64
	CatalogID field.Int64
	Name      field.String
	IsTrial   field.Int32  // 1：试看，-1：付费
	Status    field.Int32  // 1：正常，-1：下架
	Cover     field.String // 封面
	Detail    field.String // 详情
	Homework  field.String // 作业
	Sort      field.Int64
	UpdateAt  field.Time
	UpdateBy  field.Int64

	fieldMap map[string]field.Expr
}

func (g goodsCatalogDetail) Table(newTableName string) *goodsCatalogDetail {
	g.goodsCatalogDetailDo.UseTable(newTableName)
	return g.updateTableName(newTableName)
}

func (g goodsCatalogDetail) As(alias string) *goodsCatalogDetail {
	g.goodsCatalogDetailDo.DO = *(g.goodsCatalogDetailDo.As(alias).(*gen.DO))
	return g.updateTableName(alias)
}

func (g *goodsCatalogDetail) updateTableName(table string) *goodsCatalogDetail {
	g.ALL = field.NewAsterisk(table)
	g.ID = field.NewInt64(table, "id")
	g.GoodsID = field.NewInt64(table, "goods_id")
	g.CatalogID = field.NewInt64(table, "catalog_id")
	g.Name = field.NewString(table, "name")
	g.IsTrial = field.NewInt32(table, "is_trial")
	g.Status = field.NewInt32(table, "status")
	g.Cover = field.NewString(table, "cover")
	g.Detail = field.NewString(table, "detail")
	g.Homework = field.NewString(table, "homework")
	g.Sort = field.NewInt64(table, "sort")
	g.UpdateAt = field.NewTime(table, "update_at")
	g.UpdateBy = field.NewInt64(table, "update_by")

	g.fillFieldMap()

	return g
}

func (g *goodsCatalogDetail) WithContext(ctx context.Context) *goodsCatalogDetailDo {
	return g.goodsCatalogDetailDo.WithContext(ctx)
}

func (g goodsCatalogDetail) TableName() string { return g.goodsCatalogDetailDo.TableName() }

func (g goodsCatalogDetail) Alias() string { return g.goodsCatalogDetailDo.Alias() }

func (g goodsCatalogDetail) Columns(cols ...field.Expr) gen.Columns {
	return g.goodsCatalogDetailDo.Columns(cols...)
}

func (g *goodsCatalogDetail) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := g.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (g *goodsCatalogDetail) fillFieldMap() {
	g.fieldMap = make(map[string]field.Expr, 12)
	g.fieldMap["id"] = g.ID
	g.fieldMap["goods_id"] = g.GoodsID
	g.fieldMap["catalog_id"] = g.CatalogID
	g.fieldMap["name"] = g.Name
	g.fieldMap["is_trial"] = g.IsTrial
	g.fieldMap["status"] = g.Status
	g.fieldMap["cover"] = g.Cover
	g.fieldMap["detail"] = g.Detail
	g.fieldMap["homework"] = g.Homework
	g.fieldMap["sort"] = g.Sort
	g.fieldMap["update_at"] = g.UpdateAt
	g.fieldMap["update_by"] = g.UpdateBy
}

func (g goodsCatalogDetail) clone(db *gorm.DB) goodsCatalogDetail {
	g.goodsCatalogDetailDo.ReplaceConnPool(db.Statement.ConnPool)
	return g
}

func (g goodsCatalogDetail) replaceDB(db *gorm.DB) goodsCatalogDetail {
	g.goodsCatalogDetailDo.ReplaceDB(db)
	return g
}

type goodsCatalogDetailDo struct{ gen.DO }

func (g goodsCatalogDetailDo) Debug() *goodsCatalogDetailDo {
	return g.withDO(g.DO.Debug())
}

func (g goodsCatalogDetailDo) WithContext(ctx context.Context) *goodsCatalogDetailDo {
	return g.withDO(g.DO.WithContext(ctx))
}

func (g goodsCatalogDetailDo) ReadDB() *goodsCatalogDetailDo {
	return g.Clauses(dbresolver.Read)
}

func (g goodsCatalogDetailDo) WriteDB() *goodsCatalogDetailDo {
	return g.Clauses(dbresolver.Write)
}

func (g goodsCatalogDetailDo) Session(config *gorm.Session) *goodsCatalogDetailDo {
	return g.withDO(g.DO.Session(config))
}

func (g goodsCatalogDetailDo) Clauses(conds ...clause.Expression) *goodsCatalogDetailDo {
	return g.withDO(g.DO.Clauses(conds...))
}

func (g goodsCatalogDetailDo) Returning(value interface{}, columns ...string) *goodsCatalogDetailDo {
	return g.withDO(g.DO.Returning(value, columns...))
}

func (g goodsCatalogDetailDo) Not(conds ...gen.Condition) *goodsCatalogDetailDo {
	return g.withDO(g.DO.Not(conds...))
}

func (g goodsCatalogDetailDo) Or(conds ...gen.Condition) *goodsCatalogDetailDo {
	return g.withDO(g.DO.Or(conds...))
}

func (g goodsCatalogDetailDo) Select(conds ...field.Expr) *goodsCatalogDetailDo {
	return g.withDO(g.DO.Select(conds...))
}

func (g goodsCatalogDetailDo) Where(conds ...gen.Condition) *goodsCatalogDetailDo {
	return g.withDO(g.DO.Where(conds...))
}

func (g goodsCatalogDetailDo) Order(conds ...field.Expr) *goodsCatalogDetailDo {
	return g.withDO(g.DO.Order(conds...))
}

func (g goodsCatalogDetailDo) Distinct(cols ...field.Expr) *goodsCatalogDetailDo {
	return g.withDO(g.DO.Distinct(cols...))
}

func (g goodsCatalogDetailDo) Omit(cols ...field.Expr) *goodsCatalogDetailDo {
	return g.withDO(g.DO.Omit(cols...))
}

func (g goodsCatalogDetailDo) Join(table schema.Tabler, on ...field.Expr) *goodsCatalogDetailDo {
	return g.withDO(g.DO.Join(table, on...))
}

func (g goodsCatalogDetailDo) LeftJoin(table schema.Tabler, on ...field.Expr) *goodsCatalogDetailDo {
	return g.withDO(g.DO.LeftJoin(table, on...))
}

func (g goodsCatalogDetailDo) RightJoin(table schema.Tabler, on ...field.Expr) *goodsCatalogDetailDo {
	return g.withDO(g.DO.RightJoin(table, on...))
}

func (g goodsCatalogDetailDo) Group(cols ...field.Expr) *goodsCatalogDetailDo {
	return g.withDO(g.DO.Group(cols...))
}

func (g goodsCatalogDetailDo) Having(conds ...gen.Condition) *goodsCatalogDetailDo {
	return g.withDO(g.DO.Having(conds...))
}

func (g goodsCatalogDetailDo) Limit(limit int) *goodsCatalogDetailDo {
	return g.withDO(g.DO.Limit(limit))
}

func (g goodsCatalogDetailDo) Offset(offset int) *goodsCatalogDetailDo {
	return g.withDO(g.DO.Offset(offset))
}

func (g goodsCatalogDetailDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *goodsCatalogDetailDo {
	return g.withDO(g.DO.Scopes(funcs...))
}

func (g goodsCatalogDetailDo) Unscoped() *goodsCatalogDetailDo {
	return g.withDO(g.DO.Unscoped())
}

func (g goodsCatalogDetailDo) Create(values ...*model.GoodsCatalogDetail) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Create(values)
}

func (g goodsCatalogDetailDo) CreateInBatches(values []*model.GoodsCatalogDetail, batchSize int) error {
	return g.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (g goodsCatalogDetailDo) Save(values ...*model.GoodsCatalogDetail) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Save(values)
}

func (g goodsCatalogDetailDo) First() (*model.GoodsCatalogDetail, error) {
	if result, err := g.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.GoodsCatalogDetail), nil
	}
}

func (g goodsCatalogDetailDo) Take() (*model.GoodsCatalogDetail, error) {
	if result, err := g.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.GoodsCatalogDetail), nil
	}
}

func (g goodsCatalogDetailDo) Last() (*model.GoodsCatalogDetail, error) {
	if result, err := g.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.GoodsCatalogDetail), nil
	}
}

func (g goodsCatalogDetailDo) Find() ([]*model.GoodsCatalogDetail, error) {
	result, err := g.DO.Find()
	return result.([]*model.GoodsCatalogDetail), err
}

func (g goodsCatalogDetailDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.GoodsCatalogDetail, err error) {
	buf := make([]*model.GoodsCatalogDetail, 0, batchSize)
	err = g.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (g goodsCatalogDetailDo) FindInBatches(result *[]*model.GoodsCatalogDetail, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return g.DO.FindInBatches(result, batchSize, fc)
}

func (g goodsCatalogDetailDo) Attrs(attrs ...field.AssignExpr) *goodsCatalogDetailDo {
	return g.withDO(g.DO.Attrs(attrs...))
}

func (g goodsCatalogDetailDo) Assign(attrs ...field.AssignExpr) *goodsCatalogDetailDo {
	return g.withDO(g.DO.Assign(attrs...))
}

func (g goodsCatalogDetailDo) Joins(fields ...field.RelationField) *goodsCatalogDetailDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Joins(_f))
	}
	return &g
}

func (g goodsCatalogDetailDo) Preload(fields ...field.RelationField) *goodsCatalogDetailDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Preload(_f))
	}
	return &g
}

func (g goodsCatalogDetailDo) FirstOrInit() (*model.GoodsCatalogDetail, error) {
	if result, err := g.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.GoodsCatalogDetail), nil
	}
}

func (g goodsCatalogDetailDo) FirstOrCreate() (*model.GoodsCatalogDetail, error) {
	if result, err := g.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.GoodsCatalogDetail), nil
	}
}

func (g goodsCatalogDetailDo) FindByPage(offset int, limit int) (result []*model.GoodsCatalogDetail, count int64, err error) {
	result, err = g.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = g.Offset(-1).Limit(-1).Count()
	return
}

func (g goodsCatalogDetailDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = g.Count()
	if err != nil {
		return
	}

	err = g.Offset(offset).Limit(limit).Scan(result)
	return
}

func (g goodsCatalogDetailDo) Scan(result interface{}) (err error) {
	return g.DO.Scan(result)
}

func (g goodsCatalogDetailDo) Delete(models ...*model.GoodsCatalogDetail) (result gen.ResultInfo, err error) {
	return g.DO.Delete(models)
}

func (g *goodsCatalogDetailDo) withDO(do gen.Dao) *goodsCatalogDetailDo {
	g.DO = *do.(*gen.DO)
	return g
}
