// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"workspace-goshow-mall/adaptor/repo/model"
)

func newGoodsCatalog(db *gorm.DB, opts ...gen.DOOption) goodsCatalog {
	_goodsCatalog := goodsCatalog{}

	_goodsCatalog.goodsCatalogDo.UseDB(db, opts...)
	_goodsCatalog.goodsCatalogDo.UseModel(&model.GoodsCatalog{})

	tableName := _goodsCatalog.goodsCatalogDo.TableName()
	_goodsCatalog.ALL = field.NewAsterisk(tableName)
	_goodsCatalog.ID = field.NewInt64(tableName, "id")
	_goodsCatalog.ParentID = field.NewInt64(tableName, "parent_id")
	_goodsCatalog.Level = field.NewInt32(tableName, "level")
	_goodsCatalog.Name = field.NewString(tableName, "name")
	_goodsCatalog.GoodsID = field.NewInt64(tableName, "goods_id")
	_goodsCatalog.Sort = field.NewInt64(tableName, "sort")
	_goodsCatalog.UpdateAt = field.NewTime(tableName, "update_at")
	_goodsCatalog.UpdateBy = field.NewInt64(tableName, "update_by")

	_goodsCatalog.fillFieldMap()

	return _goodsCatalog
}

// goodsCatalog 商品目录表
type goodsCatalog struct {
	goodsCatalogDo goodsCatalogDo

	ALL      field.Asterisk
	ID       field.Int64
	ParentID field.Int64
	Level    field.Int32
	Name     field.String
	GoodsID  field.Int64
	Sort     field.Int64
	UpdateAt field.Time
	UpdateBy field.Int64

	fieldMap map[string]field.Expr
}

func (g goodsCatalog) Table(newTableName string) *goodsCatalog {
	g.goodsCatalogDo.UseTable(newTableName)
	return g.updateTableName(newTableName)
}

func (g goodsCatalog) As(alias string) *goodsCatalog {
	g.goodsCatalogDo.DO = *(g.goodsCatalogDo.As(alias).(*gen.DO))
	return g.updateTableName(alias)
}

func (g *goodsCatalog) updateTableName(table string) *goodsCatalog {
	g.ALL = field.NewAsterisk(table)
	g.ID = field.NewInt64(table, "id")
	g.ParentID = field.NewInt64(table, "parent_id")
	g.Level = field.NewInt32(table, "level")
	g.Name = field.NewString(table, "name")
	g.GoodsID = field.NewInt64(table, "goods_id")
	g.Sort = field.NewInt64(table, "sort")
	g.UpdateAt = field.NewTime(table, "update_at")
	g.UpdateBy = field.NewInt64(table, "update_by")

	g.fillFieldMap()

	return g
}

func (g *goodsCatalog) WithContext(ctx context.Context) *goodsCatalogDo {
	return g.goodsCatalogDo.WithContext(ctx)
}

func (g goodsCatalog) TableName() string { return g.goodsCatalogDo.TableName() }

func (g goodsCatalog) Alias() string { return g.goodsCatalogDo.Alias() }

func (g goodsCatalog) Columns(cols ...field.Expr) gen.Columns {
	return g.goodsCatalogDo.Columns(cols...)
}

func (g *goodsCatalog) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := g.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (g *goodsCatalog) fillFieldMap() {
	g.fieldMap = make(map[string]field.Expr, 8)
	g.fieldMap["id"] = g.ID
	g.fieldMap["parent_id"] = g.ParentID
	g.fieldMap["level"] = g.Level
	g.fieldMap["name"] = g.Name
	g.fieldMap["goods_id"] = g.GoodsID
	g.fieldMap["sort"] = g.Sort
	g.fieldMap["update_at"] = g.UpdateAt
	g.fieldMap["update_by"] = g.UpdateBy
}

func (g goodsCatalog) clone(db *gorm.DB) goodsCatalog {
	g.goodsCatalogDo.ReplaceConnPool(db.Statement.ConnPool)
	return g
}

func (g goodsCatalog) replaceDB(db *gorm.DB) goodsCatalog {
	g.goodsCatalogDo.ReplaceDB(db)
	return g
}

type goodsCatalogDo struct{ gen.DO }

func (g goodsCatalogDo) Debug() *goodsCatalogDo {
	return g.withDO(g.DO.Debug())
}

func (g goodsCatalogDo) WithContext(ctx context.Context) *goodsCatalogDo {
	return g.withDO(g.DO.WithContext(ctx))
}

func (g goodsCatalogDo) ReadDB() *goodsCatalogDo {
	return g.Clauses(dbresolver.Read)
}

func (g goodsCatalogDo) WriteDB() *goodsCatalogDo {
	return g.Clauses(dbresolver.Write)
}

func (g goodsCatalogDo) Session(config *gorm.Session) *goodsCatalogDo {
	return g.withDO(g.DO.Session(config))
}

func (g goodsCatalogDo) Clauses(conds ...clause.Expression) *goodsCatalogDo {
	return g.withDO(g.DO.Clauses(conds...))
}

func (g goodsCatalogDo) Returning(value interface{}, columns ...string) *goodsCatalogDo {
	return g.withDO(g.DO.Returning(value, columns...))
}

func (g goodsCatalogDo) Not(conds ...gen.Condition) *goodsCatalogDo {
	return g.withDO(g.DO.Not(conds...))
}

func (g goodsCatalogDo) Or(conds ...gen.Condition) *goodsCatalogDo {
	return g.withDO(g.DO.Or(conds...))
}

func (g goodsCatalogDo) Select(conds ...field.Expr) *goodsCatalogDo {
	return g.withDO(g.DO.Select(conds...))
}

func (g goodsCatalogDo) Where(conds ...gen.Condition) *goodsCatalogDo {
	return g.withDO(g.DO.Where(conds...))
}

func (g goodsCatalogDo) Order(conds ...field.Expr) *goodsCatalogDo {
	return g.withDO(g.DO.Order(conds...))
}

func (g goodsCatalogDo) Distinct(cols ...field.Expr) *goodsCatalogDo {
	return g.withDO(g.DO.Distinct(cols...))
}

func (g goodsCatalogDo) Omit(cols ...field.Expr) *goodsCatalogDo {
	return g.withDO(g.DO.Omit(cols...))
}

func (g goodsCatalogDo) Join(table schema.Tabler, on ...field.Expr) *goodsCatalogDo {
	return g.withDO(g.DO.Join(table, on...))
}

func (g goodsCatalogDo) LeftJoin(table schema.Tabler, on ...field.Expr) *goodsCatalogDo {
	return g.withDO(g.DO.LeftJoin(table, on...))
}

func (g goodsCatalogDo) RightJoin(table schema.Tabler, on ...field.Expr) *goodsCatalogDo {
	return g.withDO(g.DO.RightJoin(table, on...))
}

func (g goodsCatalogDo) Group(cols ...field.Expr) *goodsCatalogDo {
	return g.withDO(g.DO.Group(cols...))
}

func (g goodsCatalogDo) Having(conds ...gen.Condition) *goodsCatalogDo {
	return g.withDO(g.DO.Having(conds...))
}

func (g goodsCatalogDo) Limit(limit int) *goodsCatalogDo {
	return g.withDO(g.DO.Limit(limit))
}

func (g goodsCatalogDo) Offset(offset int) *goodsCatalogDo {
	return g.withDO(g.DO.Offset(offset))
}

func (g goodsCatalogDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *goodsCatalogDo {
	return g.withDO(g.DO.Scopes(funcs...))
}

func (g goodsCatalogDo) Unscoped() *goodsCatalogDo {
	return g.withDO(g.DO.Unscoped())
}

func (g goodsCatalogDo) Create(values ...*model.GoodsCatalog) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Create(values)
}

func (g goodsCatalogDo) CreateInBatches(values []*model.GoodsCatalog, batchSize int) error {
	return g.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (g goodsCatalogDo) Save(values ...*model.GoodsCatalog) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Save(values)
}

func (g goodsCatalogDo) First() (*model.GoodsCatalog, error) {
	if result, err := g.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.GoodsCatalog), nil
	}
}

func (g goodsCatalogDo) Take() (*model.GoodsCatalog, error) {
	if result, err := g.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.GoodsCatalog), nil
	}
}

func (g goodsCatalogDo) Last() (*model.GoodsCatalog, error) {
	if result, err := g.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.GoodsCatalog), nil
	}
}

func (g goodsCatalogDo) Find() ([]*model.GoodsCatalog, error) {
	result, err := g.DO.Find()
	return result.([]*model.GoodsCatalog), err
}

func (g goodsCatalogDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.GoodsCatalog, err error) {
	buf := make([]*model.GoodsCatalog, 0, batchSize)
	err = g.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (g goodsCatalogDo) FindInBatches(result *[]*model.GoodsCatalog, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return g.DO.FindInBatches(result, batchSize, fc)
}

func (g goodsCatalogDo) Attrs(attrs ...field.AssignExpr) *goodsCatalogDo {
	return g.withDO(g.DO.Attrs(attrs...))
}

func (g goodsCatalogDo) Assign(attrs ...field.AssignExpr) *goodsCatalogDo {
	return g.withDO(g.DO.Assign(attrs...))
}

func (g goodsCatalogDo) Joins(fields ...field.RelationField) *goodsCatalogDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Joins(_f))
	}
	return &g
}

func (g goodsCatalogDo) Preload(fields ...field.RelationField) *goodsCatalogDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Preload(_f))
	}
	return &g
}

func (g goodsCatalogDo) FirstOrInit() (*model.GoodsCatalog, error) {
	if result, err := g.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.GoodsCatalog), nil
	}
}

func (g goodsCatalogDo) FirstOrCreate() (*model.GoodsCatalog, error) {
	if result, err := g.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.GoodsCatalog), nil
	}
}

func (g goodsCatalogDo) FindByPage(offset int, limit int) (result []*model.GoodsCatalog, count int64, err error) {
	result, err = g.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = g.Offset(-1).Limit(-1).Count()
	return
}

func (g goodsCatalogDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = g.Count()
	if err != nil {
		return
	}

	err = g.Offset(offset).Limit(limit).Scan(result)
	return
}

func (g goodsCatalogDo) Scan(result interface{}) (err error) {
	return g.DO.Scan(result)
}

func (g goodsCatalogDo) Delete(models ...*model.GoodsCatalog) (result gen.ResultInfo, err error) {
	return g.DO.Delete(models)
}

func (g *goodsCatalogDo) withDO(do gen.Dao) *goodsCatalogDo {
	g.DO = *do.(*gen.DO)
	return g
}
