// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                 db,
		Admin:              newAdmin(db, opts...),
		AppUser:            newAppUser(db, opts...),
		Good:               newGood(db, opts...),
		GoodsCatalog:       newGoodsCatalog(db, opts...),
		GoodsCatalogDetail: newGoodsCatalogDetail(db, opts...),
		MobileUser:         newMobileUser(db, opts...),
		Order:              newOrder(db, opts...),
		OrderItem:          newOrderItem(db, opts...),
		Permission:         newPermission(db, opts...),
		Role:               newRole(db, opts...),
		RolePermission:     newRolePermission(db, opts...),
		SmsTemplate:        newSmsTemplate(db, opts...),
		UploadFile:         newUploadFile(db, opts...),
		User:               newUser(db, opts...),
		UserGood:           newUserGood(db, opts...),
		WechatUser:         newWechatUser(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Admin              admin
	AppUser            appUser
	Good               good
	GoodsCatalog       goodsCatalog
	GoodsCatalogDetail goodsCatalogDetail
	MobileUser         mobileUser
	Order              order
	OrderItem          orderItem
	Permission         permission
	Role               role
	RolePermission     rolePermission
	SmsTemplate        smsTemplate
	UploadFile         uploadFile
	User               user
	UserGood           userGood
	WechatUser         wechatUser
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                 db,
		Admin:              q.Admin.clone(db),
		AppUser:            q.AppUser.clone(db),
		Good:               q.Good.clone(db),
		GoodsCatalog:       q.GoodsCatalog.clone(db),
		GoodsCatalogDetail: q.GoodsCatalogDetail.clone(db),
		MobileUser:         q.MobileUser.clone(db),
		Order:              q.Order.clone(db),
		OrderItem:          q.OrderItem.clone(db),
		Permission:         q.Permission.clone(db),
		Role:               q.Role.clone(db),
		RolePermission:     q.RolePermission.clone(db),
		SmsTemplate:        q.SmsTemplate.clone(db),
		UploadFile:         q.UploadFile.clone(db),
		User:               q.User.clone(db),
		UserGood:           q.UserGood.clone(db),
		WechatUser:         q.WechatUser.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                 db,
		Admin:              q.Admin.replaceDB(db),
		AppUser:            q.AppUser.replaceDB(db),
		Good:               q.Good.replaceDB(db),
		GoodsCatalog:       q.GoodsCatalog.replaceDB(db),
		GoodsCatalogDetail: q.GoodsCatalogDetail.replaceDB(db),
		MobileUser:         q.MobileUser.replaceDB(db),
		Order:              q.Order.replaceDB(db),
		OrderItem:          q.OrderItem.replaceDB(db),
		Permission:         q.Permission.replaceDB(db),
		Role:               q.Role.replaceDB(db),
		RolePermission:     q.RolePermission.replaceDB(db),
		SmsTemplate:        q.SmsTemplate.replaceDB(db),
		UploadFile:         q.UploadFile.replaceDB(db),
		User:               q.User.replaceDB(db),
		UserGood:           q.UserGood.replaceDB(db),
		WechatUser:         q.WechatUser.replaceDB(db),
	}
}

type queryCtx struct {
	Admin              *adminDo
	AppUser            *appUserDo
	Good               *goodDo
	GoodsCatalog       *goodsCatalogDo
	GoodsCatalogDetail *goodsCatalogDetailDo
	MobileUser         *mobileUserDo
	Order              *orderDo
	OrderItem          *orderItemDo
	Permission         *permissionDo
	Role               *roleDo
	RolePermission     *rolePermissionDo
	SmsTemplate        *smsTemplateDo
	UploadFile         *uploadFileDo
	User               *userDo
	UserGood           *userGoodDo
	WechatUser         *wechatUserDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Admin:              q.Admin.WithContext(ctx),
		AppUser:            q.AppUser.WithContext(ctx),
		Good:               q.Good.WithContext(ctx),
		GoodsCatalog:       q.GoodsCatalog.WithContext(ctx),
		GoodsCatalogDetail: q.GoodsCatalogDetail.WithContext(ctx),
		MobileUser:         q.MobileUser.WithContext(ctx),
		Order:              q.Order.WithContext(ctx),
		OrderItem:          q.OrderItem.WithContext(ctx),
		Permission:         q.Permission.WithContext(ctx),
		Role:               q.Role.WithContext(ctx),
		RolePermission:     q.RolePermission.WithContext(ctx),
		SmsTemplate:        q.SmsTemplate.WithContext(ctx),
		UploadFile:         q.UploadFile.WithContext(ctx),
		User:               q.User.WithContext(ctx),
		UserGood:           q.UserGood.WithContext(ctx),
		WechatUser:         q.WechatUser.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
