// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"workspace-goshow-mall/adaptor/repo/model"
)

func newUploadFile(db *gorm.DB, opts ...gen.DOOption) uploadFile {
	_uploadFile := uploadFile{}

	_uploadFile.uploadFileDo.UseDB(db, opts...)
	_uploadFile.uploadFileDo.UseModel(&model.UploadFile{})

	tableName := _uploadFile.uploadFileDo.TableName()
	_uploadFile.ALL = field.NewAsterisk(tableName)
	_uploadFile.ID = field.NewInt64(tableName, "id")
	_uploadFile.Scene = field.NewString(tableName, "scene")
	_uploadFile.FileKey = field.NewString(tableName, "file_key")
	_uploadFile.UserID = field.NewInt64(tableName, "user_id")
	_uploadFile.UserType = field.NewInt32(tableName, "user_type")
	_uploadFile.FileType = field.NewString(tableName, "file_type")
	_uploadFile.FileSize = field.NewInt64(tableName, "file_size")
	_uploadFile.FileName = field.NewString(tableName, "file_name")
	_uploadFile.UploadIP = field.NewString(tableName, "upload_ip")
	_uploadFile.CreateAt = field.NewTime(tableName, "create_at")

	_uploadFile.fillFieldMap()

	return _uploadFile
}

// uploadFile 云对象存储上传文件表
type uploadFile struct {
	uploadFileDo uploadFileDo

	ALL      field.Asterisk
	ID       field.Int64
	Scene    field.String // 业务场景
	FileKey  field.String // 云存储key
	UserID   field.Int64
	UserType field.Int32  // 1：普通用户，2：管理员
	FileType field.String // 文件类型
	FileSize field.Int64  // 文件字节数
	FileName field.String // 文件名
	UploadIP field.String // 上传ip
	CreateAt field.Time

	fieldMap map[string]field.Expr
}

func (u uploadFile) Table(newTableName string) *uploadFile {
	u.uploadFileDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u uploadFile) As(alias string) *uploadFile {
	u.uploadFileDo.DO = *(u.uploadFileDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *uploadFile) updateTableName(table string) *uploadFile {
	u.ALL = field.NewAsterisk(table)
	u.ID = field.NewInt64(table, "id")
	u.Scene = field.NewString(table, "scene")
	u.FileKey = field.NewString(table, "file_key")
	u.UserID = field.NewInt64(table, "user_id")
	u.UserType = field.NewInt32(table, "user_type")
	u.FileType = field.NewString(table, "file_type")
	u.FileSize = field.NewInt64(table, "file_size")
	u.FileName = field.NewString(table, "file_name")
	u.UploadIP = field.NewString(table, "upload_ip")
	u.CreateAt = field.NewTime(table, "create_at")

	u.fillFieldMap()

	return u
}

func (u *uploadFile) WithContext(ctx context.Context) *uploadFileDo {
	return u.uploadFileDo.WithContext(ctx)
}

func (u uploadFile) TableName() string { return u.uploadFileDo.TableName() }

func (u uploadFile) Alias() string { return u.uploadFileDo.Alias() }

func (u uploadFile) Columns(cols ...field.Expr) gen.Columns { return u.uploadFileDo.Columns(cols...) }

func (u *uploadFile) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *uploadFile) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 10)
	u.fieldMap["id"] = u.ID
	u.fieldMap["scene"] = u.Scene
	u.fieldMap["file_key"] = u.FileKey
	u.fieldMap["user_id"] = u.UserID
	u.fieldMap["user_type"] = u.UserType
	u.fieldMap["file_type"] = u.FileType
	u.fieldMap["file_size"] = u.FileSize
	u.fieldMap["file_name"] = u.FileName
	u.fieldMap["upload_ip"] = u.UploadIP
	u.fieldMap["create_at"] = u.CreateAt
}

func (u uploadFile) clone(db *gorm.DB) uploadFile {
	u.uploadFileDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u uploadFile) replaceDB(db *gorm.DB) uploadFile {
	u.uploadFileDo.ReplaceDB(db)
	return u
}

type uploadFileDo struct{ gen.DO }

func (u uploadFileDo) Debug() *uploadFileDo {
	return u.withDO(u.DO.Debug())
}

func (u uploadFileDo) WithContext(ctx context.Context) *uploadFileDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u uploadFileDo) ReadDB() *uploadFileDo {
	return u.Clauses(dbresolver.Read)
}

func (u uploadFileDo) WriteDB() *uploadFileDo {
	return u.Clauses(dbresolver.Write)
}

func (u uploadFileDo) Session(config *gorm.Session) *uploadFileDo {
	return u.withDO(u.DO.Session(config))
}

func (u uploadFileDo) Clauses(conds ...clause.Expression) *uploadFileDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u uploadFileDo) Returning(value interface{}, columns ...string) *uploadFileDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u uploadFileDo) Not(conds ...gen.Condition) *uploadFileDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u uploadFileDo) Or(conds ...gen.Condition) *uploadFileDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u uploadFileDo) Select(conds ...field.Expr) *uploadFileDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u uploadFileDo) Where(conds ...gen.Condition) *uploadFileDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u uploadFileDo) Order(conds ...field.Expr) *uploadFileDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u uploadFileDo) Distinct(cols ...field.Expr) *uploadFileDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u uploadFileDo) Omit(cols ...field.Expr) *uploadFileDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u uploadFileDo) Join(table schema.Tabler, on ...field.Expr) *uploadFileDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u uploadFileDo) LeftJoin(table schema.Tabler, on ...field.Expr) *uploadFileDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u uploadFileDo) RightJoin(table schema.Tabler, on ...field.Expr) *uploadFileDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u uploadFileDo) Group(cols ...field.Expr) *uploadFileDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u uploadFileDo) Having(conds ...gen.Condition) *uploadFileDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u uploadFileDo) Limit(limit int) *uploadFileDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u uploadFileDo) Offset(offset int) *uploadFileDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u uploadFileDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *uploadFileDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u uploadFileDo) Unscoped() *uploadFileDo {
	return u.withDO(u.DO.Unscoped())
}

func (u uploadFileDo) Create(values ...*model.UploadFile) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u uploadFileDo) CreateInBatches(values []*model.UploadFile, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u uploadFileDo) Save(values ...*model.UploadFile) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u uploadFileDo) First() (*model.UploadFile, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.UploadFile), nil
	}
}

func (u uploadFileDo) Take() (*model.UploadFile, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.UploadFile), nil
	}
}

func (u uploadFileDo) Last() (*model.UploadFile, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.UploadFile), nil
	}
}

func (u uploadFileDo) Find() ([]*model.UploadFile, error) {
	result, err := u.DO.Find()
	return result.([]*model.UploadFile), err
}

func (u uploadFileDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UploadFile, err error) {
	buf := make([]*model.UploadFile, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u uploadFileDo) FindInBatches(result *[]*model.UploadFile, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u uploadFileDo) Attrs(attrs ...field.AssignExpr) *uploadFileDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u uploadFileDo) Assign(attrs ...field.AssignExpr) *uploadFileDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u uploadFileDo) Joins(fields ...field.RelationField) *uploadFileDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u uploadFileDo) Preload(fields ...field.RelationField) *uploadFileDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u uploadFileDo) FirstOrInit() (*model.UploadFile, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.UploadFile), nil
	}
}

func (u uploadFileDo) FirstOrCreate() (*model.UploadFile, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.UploadFile), nil
	}
}

func (u uploadFileDo) FindByPage(offset int, limit int) (result []*model.UploadFile, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u uploadFileDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u uploadFileDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u uploadFileDo) Delete(models ...*model.UploadFile) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *uploadFileDo) withDO(do gen.Dao) *uploadFileDo {
	u.DO = *do.(*gen.DO)
	return u
}
