// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"workspace-goshow-mall/adaptor/repo/model"
)

func newUserGood(db *gorm.DB, opts ...gen.DOOption) userGood {
	_userGood := userGood{}

	_userGood.userGoodDo.UseDB(db, opts...)
	_userGood.userGoodDo.UseModel(&model.UserGood{})

	tableName := _userGood.userGoodDo.TableName()
	_userGood.ALL = field.NewAsterisk(tableName)
	_userGood.ID = field.NewInt64(tableName, "id")
	_userGood.UserID = field.NewInt64(tableName, "user_id")
	_userGood.OrderID = field.NewInt64(tableName, "order_id")
	_userGood.GoodsID = field.NewInt64(tableName, "goods_id")
	_userGood.GoodsType = field.NewInt32(tableName, "goods_type")
	_userGood.BuyTime = field.NewInt64(tableName, "buy_time")
	_userGood.ExpireTime = field.NewInt64(tableName, "expire_time")

	_userGood.fillFieldMap()

	return _userGood
}

// userGood 用户购买商品表
type userGood struct {
	userGoodDo userGoodDo

	ALL        field.Asterisk
	ID         field.Int64
	UserID     field.Int64 // 用户id
	OrderID    field.Int64 // 订单id
	GoodsID    field.Int64 // 商品id
	GoodsType  field.Int32 // 商品类型
	BuyTime    field.Int64 // 购买时间
	ExpireTime field.Int64 // 到期时间

	fieldMap map[string]field.Expr
}

func (u userGood) Table(newTableName string) *userGood {
	u.userGoodDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u userGood) As(alias string) *userGood {
	u.userGoodDo.DO = *(u.userGoodDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *userGood) updateTableName(table string) *userGood {
	u.ALL = field.NewAsterisk(table)
	u.ID = field.NewInt64(table, "id")
	u.UserID = field.NewInt64(table, "user_id")
	u.OrderID = field.NewInt64(table, "order_id")
	u.GoodsID = field.NewInt64(table, "goods_id")
	u.GoodsType = field.NewInt32(table, "goods_type")
	u.BuyTime = field.NewInt64(table, "buy_time")
	u.ExpireTime = field.NewInt64(table, "expire_time")

	u.fillFieldMap()

	return u
}

func (u *userGood) WithContext(ctx context.Context) *userGoodDo { return u.userGoodDo.WithContext(ctx) }

func (u userGood) TableName() string { return u.userGoodDo.TableName() }

func (u userGood) Alias() string { return u.userGoodDo.Alias() }

func (u userGood) Columns(cols ...field.Expr) gen.Columns { return u.userGoodDo.Columns(cols...) }

func (u *userGood) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *userGood) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 7)
	u.fieldMap["id"] = u.ID
	u.fieldMap["user_id"] = u.UserID
	u.fieldMap["order_id"] = u.OrderID
	u.fieldMap["goods_id"] = u.GoodsID
	u.fieldMap["goods_type"] = u.GoodsType
	u.fieldMap["buy_time"] = u.BuyTime
	u.fieldMap["expire_time"] = u.ExpireTime
}

func (u userGood) clone(db *gorm.DB) userGood {
	u.userGoodDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u userGood) replaceDB(db *gorm.DB) userGood {
	u.userGoodDo.ReplaceDB(db)
	return u
}

type userGoodDo struct{ gen.DO }

func (u userGoodDo) Debug() *userGoodDo {
	return u.withDO(u.DO.Debug())
}

func (u userGoodDo) WithContext(ctx context.Context) *userGoodDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u userGoodDo) ReadDB() *userGoodDo {
	return u.Clauses(dbresolver.Read)
}

func (u userGoodDo) WriteDB() *userGoodDo {
	return u.Clauses(dbresolver.Write)
}

func (u userGoodDo) Session(config *gorm.Session) *userGoodDo {
	return u.withDO(u.DO.Session(config))
}

func (u userGoodDo) Clauses(conds ...clause.Expression) *userGoodDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u userGoodDo) Returning(value interface{}, columns ...string) *userGoodDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u userGoodDo) Not(conds ...gen.Condition) *userGoodDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u userGoodDo) Or(conds ...gen.Condition) *userGoodDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u userGoodDo) Select(conds ...field.Expr) *userGoodDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u userGoodDo) Where(conds ...gen.Condition) *userGoodDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u userGoodDo) Order(conds ...field.Expr) *userGoodDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u userGoodDo) Distinct(cols ...field.Expr) *userGoodDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u userGoodDo) Omit(cols ...field.Expr) *userGoodDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u userGoodDo) Join(table schema.Tabler, on ...field.Expr) *userGoodDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u userGoodDo) LeftJoin(table schema.Tabler, on ...field.Expr) *userGoodDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u userGoodDo) RightJoin(table schema.Tabler, on ...field.Expr) *userGoodDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u userGoodDo) Group(cols ...field.Expr) *userGoodDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u userGoodDo) Having(conds ...gen.Condition) *userGoodDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u userGoodDo) Limit(limit int) *userGoodDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u userGoodDo) Offset(offset int) *userGoodDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u userGoodDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *userGoodDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u userGoodDo) Unscoped() *userGoodDo {
	return u.withDO(u.DO.Unscoped())
}

func (u userGoodDo) Create(values ...*model.UserGood) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u userGoodDo) CreateInBatches(values []*model.UserGood, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u userGoodDo) Save(values ...*model.UserGood) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u userGoodDo) First() (*model.UserGood, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserGood), nil
	}
}

func (u userGoodDo) Take() (*model.UserGood, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserGood), nil
	}
}

func (u userGoodDo) Last() (*model.UserGood, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserGood), nil
	}
}

func (u userGoodDo) Find() ([]*model.UserGood, error) {
	result, err := u.DO.Find()
	return result.([]*model.UserGood), err
}

func (u userGoodDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UserGood, err error) {
	buf := make([]*model.UserGood, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u userGoodDo) FindInBatches(result *[]*model.UserGood, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u userGoodDo) Attrs(attrs ...field.AssignExpr) *userGoodDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u userGoodDo) Assign(attrs ...field.AssignExpr) *userGoodDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u userGoodDo) Joins(fields ...field.RelationField) *userGoodDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u userGoodDo) Preload(fields ...field.RelationField) *userGoodDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u userGoodDo) FirstOrInit() (*model.UserGood, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserGood), nil
	}
}

func (u userGoodDo) FirstOrCreate() (*model.UserGood, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserGood), nil
	}
}

func (u userGoodDo) FindByPage(offset int, limit int) (result []*model.UserGood, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u userGoodDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u userGoodDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u userGoodDo) Delete(models ...*model.UserGood) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *userGoodDo) withDO(do gen.Dao) *userGoodDo {
	u.DO = *do.(*gen.DO)
	return u
}
