// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAppUser = "app_user"

// AppUser 应用用户表
type AppUser struct {
	ID      int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID  int64  `gorm:"column:user_id;not null;comment:用户id" json:"user_id"`                // 用户id
	AppCode int32  `gorm:"column:app_code;not null;comment:1000：公众号，1001：小程序" json:"app_code"` // 1000：公众号，1001：小程序
	OpenID  string `gorm:"column:open_id;not null;comment:微信应用openid" json:"open_id"`          // 微信应用openid
	/*
		create_at
		update_at

	*/
	Status   int32     `gorm:"column:status;not null;default:1;comment:create_at\nupdate_at\n" json:"status"`
	CreateAt time.Time `gorm:"column:create_at;not null;default:CURRENT_TIMESTAMP" json:"create_at"`
	UpdateAt time.Time `gorm:"column:update_at;not null" json:"update_at"`
}

// TableName AppUser's table name
func (*AppUser) TableName() string {
	return TableNameAppUser
}
