// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameGoodsCatalogDetail = "goods_catalog_detail"

// GoodsCatalogDetail 商品目录详情表
type GoodsCatalogDetail struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	GoodsID   int64     `gorm:"column:goods_id;not null" json:"goods_id"`
	CatalogID int64     `gorm:"column:catalog_id;not null" json:"catalog_id"`
	Name      string    `gorm:"column:name;not null" json:"name"`
	IsTrial   int32     `gorm:"column:is_trial;not null;comment:1：试看，-1：付费" json:"is_trial"`       // 1：试看，-1：付费
	Status    int32     `gorm:"column:status;not null;default:1;comment:1：正常，-1：下架" json:"status"` // 1：正常，-1：下架
	Cover     string    `gorm:"column:cover;not null;comment:封面" json:"cover"`                     // 封面
	Detail    string    `gorm:"column:detail;not null;comment:详情" json:"detail"`                   // 详情
	Homework  string    `gorm:"column:homework;not null;comment:作业" json:"homework"`               // 作业
	Sort      int64     `gorm:"column:sort;not null" json:"sort"`
	UpdateAt  time.Time `gorm:"column:update_at;not null" json:"update_at"`
	UpdateBy  int64     `gorm:"column:update_by;not null" json:"update_by"`
}

// TableName GoodsCatalogDetail's table name
func (*GoodsCatalogDetail) TableName() string {
	return TableNameGoodsCatalogDetail
}
