// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameGood = "goods"

// Good 商品表
type Good struct {
	ID            int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name          string    `gorm:"column:name;not null" json:"name"`
	Cover         string    `gorm:"column:cover;not null;comment:商品封面" json:"cover"`                                        // 商品封面
	Introduction  string    `gorm:"column:introduction;not null;comment:商品介绍（云存储地址）" json:"introduction"`                   // 商品介绍（云存储地址）
	Price         int64     `gorm:"column:price;not null;comment:商品价格" json:"price"`                                        // 商品价格
	EffectiveTime int32     `gorm:"column:effective_time;not null;comment:有效时长 1：1个月，2：半年，3：一年，4：永久" json:"effective_time"` // 有效时长 1：1个月，2：半年，3：一年，4：永久
	Status        int32     `gorm:"column:status;not null;default:1;comment:1：正常，-1：下架" json:"status"`                      // 1：正常，-1：下架
	SaleType      int32     `gorm:"column:sale_type;not null;comment:1：免费，2：收费" json:"sale_type"`                           // 1：免费，2：收费
	CreateAt      time.Time `gorm:"column:create_at;not null;default:CURRENT_TIMESTAMP" json:"create_at"`
	UpdateAt      time.Time `gorm:"column:update_at;not null" json:"update_at"`
	CreateBy      int64     `gorm:"column:create_by;not null" json:"create_by"`
	UpdateBy      int64     `gorm:"column:update_by;not null" json:"update_by"`
}

// TableName Good's table name
func (*Good) TableName() string {
	return TableNameGood
}
