// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMobileUser = "mobile_user"

// MobileUser 手机用户表
type MobileUser struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID       int64     `gorm:"column:user_id;not null;comment:用户id" json:"user_id"`                      // 用户id
	MobileAes    string    `gorm:"column:mobile_aes;not null;comment:aes加密的手机号" json:"mobile_aes"`           // aes加密的手机号
	MobileSha256 string    `gorm:"column:mobile_sha256;not null;comment:sha256加密后的手机号" json:"mobile_sha256"` // sha256加密后的手机号
	CreateAt     time.Time `gorm:"column:create_at;not null;default:CURRENT_TIMESTAMP" json:"create_at"`
	UpdateAt     time.Time `gorm:"column:update_at;not null" json:"update_at"`
}

// TableName MobileUser's table name
func (*MobileUser) TableName() string {
	return TableNameMobileUser
}
