// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOrder = "order"

// Order 订单表
type Order struct {
	ID                 int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	OrderNumber        string    `gorm:"column:order_number;not null;comment:订单号" json:"order_number"`                    // 订单号
	UserID             int64     `gorm:"column:user_id;not null;comment:用户id" json:"user_id"`                             // 用户id
	Status             int32     `gorm:"column:status;not null;default:1;comment:1：正常，-1：下架" json:"status"`               // 1：正常，-1：下架
	OrderSource        int32     `gorm:"column:order_source;not null;comment:1：用户下单，2：管理后台，3：活动赠送" json:"order_source"`   // 1：用户下单，2：管理后台，3：活动赠送
	OrderAmount        int64     `gorm:"column:order_amount;not null;comment:订单金额" json:"order_amount"`                   // 订单金额
	OrderOrginalAmount int64     `gorm:"column:order_orginal_amount;not null;comment:订单原始金额" json:"order_orginal_amount"` // 订单原始金额
	PaymentAmount      int64     `gorm:"column:payment_amount;not null;comment:订单支付金额" json:"payment_amount"`             // 订单支付金额
	TradeNumber        string    `gorm:"column:trade_number;not null;comment:交易号" json:"trade_number"`                    // 交易号
	InnerTradeNumber   string    `gorm:"column:inner_trade_number;not null;comment:内部交易号" json:"inner_trade_number"`      // 内部交易号
	OrderDesc          string    `gorm:"column:order_desc;not null;comment:订单描述" json:"order_desc"`                       // 订单描述
	PaymentAt          int64     `gorm:"column:payment_at;not null;comment:订单交易时间" json:"payment_at"`                     // 订单交易时间
	UserRemark         string    `gorm:"column:user_remark;not null;comment:用户备注" json:"user_remark"`                     // 用户备注
	ConfirmAt          int64     `gorm:"column:confirm_at;comment:收货时间" json:"confirm_at"`                                // 收货时间
	ConfirmType        int32     `gorm:"column:confirm_type;comment:收货类型，1：用户确认，2：自动发货" json:"confirm_type"`              // 收货类型，1：用户确认，2：自动发货
	RefundAmount       int64     `gorm:"column:refund_amount;not null;comment:订单退款金额" json:"refund_amount"`               // 订单退款金额
	RefundAt           int64     `gorm:"column:refund_at;comment:退款时间" json:"refund_at"`                                  // 退款时间
	CancelAt           int64     `gorm:"column:cancel_at;comment:取消时间" json:"cancel_at"`                                  // 取消时间
	CancelBy           int64     `gorm:"column:cancel_by;comment:退款用户id" json:"cancel_by"`                                // 退款用户id
	CancelType         int32     `gorm:"column:cancel_type;comment:1：用户取消，2：超时取消，3：客服取消" json:"cancel_type"`              // 1：用户取消，2：超时取消，3：客服取消
	CancelReason       string    `gorm:"column:cancel_reason;comment:取消原因" json:"cancel_reason"`                          // 取消原因
	CreateAt           time.Time `gorm:"column:create_at;not null;default:CURRENT_TIMESTAMP" json:"create_at"`
	CreateBy           int64     `gorm:"column:create_by;not null" json:"create_by"`
}

// TableName Order's table name
func (*Order) TableName() string {
	return TableNameOrder
}
