// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameOrderItem = "order_item"

// OrderItem 订单对象表
type OrderItem struct {
	ID        int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	OrderID   int64  `gorm:"column:order_id;not null;comment:订单id" json:"order_id"` // 订单id
	UserID    int64  `gorm:"column:user_id;not null;comment:用户id" json:"user_id"`   // 用户id
	GoodsID   int64  `gorm:"column:goods_id;not null" json:"goods_id"`
	GoodsType int32  `gorm:"column:goods_type;not null;default:1;comment:1：课程，2：文本" json:"goods_type"` // 1：课程，2：文本
	Quantity  int32  `gorm:"column:quantity;not null;default:1;comment:商品数量" json:"quantity"`          // 商品数量
	GoodsSnap string `gorm:"column:goods_snap;not null;comment:商品快照" json:"goods_snap"`                // 商品快照
}

// TableName OrderItem's table name
func (*OrderItem) TableName() string {
	return TableNameOrderItem
}
