// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRole = "role"

// Role 角色表
type Role struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name        string    `gorm:"column:name;not null;comment:角色名称" json:"name"`                     // 角色名称
	Description string    `gorm:"column:description;not null;comment:角色描述" json:"description"`       // 角色描述
	Status      int32     `gorm:"column:status;not null;default:1;comment:1:正常 -1:禁用" json:"status"` // 1:正常 -1:禁用
	CreateAt    time.Time `gorm:"column:create_at;not null;default:CURRENT_TIMESTAMP" json:"create_at"`
	UpdateAt    time.Time `gorm:"column:update_at;not null;default:CURRENT_TIMESTAMP" json:"update_at"`
	CreateBy    int64     `gorm:"column:create_by;not null" json:"create_by"`
	UpdateBy    int64     `gorm:"column:update_by;not null" json:"update_by"`
}

// TableName Role's table name
func (*Role) TableName() string {
	return TableNameRole
}
