// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSmsTemplate = "sms_template"

// SmsTemplate 短信模板表
type SmsTemplate struct {
	ID            int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	SceneCode     string    `gorm:"column:scene_code;not null;comment:场景编码" json:"scene_code"`                // 场景编码
	SignName      string    `gorm:"column:sign_name;not null;comment:短信签名" json:"sign_name"`                  // 短信签名
	PlatformTmpID int32     `gorm:"column:platform_tmp_id;not null;comment:短信平台的模板id" json:"platform_tmp_id"` // 短信平台的模板id
	TmpContent    string    `gorm:"column:tmp_content;not null;comment:短信模板内容" json:"tmp_content"`            // 短信模板内容
	Status        int32     `gorm:"column:status;not null;default:1;comment:1：正常，-1：下架" json:"status"`        // 1：正常，-1：下架
	CreateAt      time.Time `gorm:"column:create_at;not null;default:CURRENT_TIMESTAMP" json:"create_at"`
	UpdateAt      time.Time `gorm:"column:update_at;not null" json:"update_at"`
	UserID        int64     `gorm:"column:user_id;not null" json:"user_id"`
	Platform      string    `gorm:"column:platform;not null" json:"platform"`
}

// TableName SmsTemplate's table name
func (*SmsTemplate) TableName() string {
	return TableNameSmsTemplate
}
