// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUploadFile = "upload_file"

// UploadFile 云对象存储上传文件表
type UploadFile struct {
	ID       int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Scene    string    `gorm:"column:scene;not null;comment:业务场景" json:"scene"`         // 业务场景
	FileKey  string    `gorm:"column:file_key;not null;comment:云存储key" json:"file_key"` // 云存储key
	UserID   int64     `gorm:"column:user_id;not null" json:"user_id"`
	UserType int32     `gorm:"column:user_type;not null;comment:1：普通用户，2：管理员" json:"user_type"` // 1：普通用户，2：管理员
	FileType string    `gorm:"column:file_type;not null;comment:文件类型" json:"file_type"`         // 文件类型
	FileSize int64     `gorm:"column:file_size;not null;comment:文件字节数" json:"file_size"`        // 文件字节数
	FileName string    `gorm:"column:file_name;not null;comment:文件名" json:"file_name"`          // 文件名
	UploadIP string    `gorm:"column:upload_ip;not null;comment:上传ip" json:"upload_ip"`         // 上传ip
	CreateAt time.Time `gorm:"column:create_at;not null;default:CURRENT_TIMESTAMP" json:"create_at"`
}

// TableName UploadFile's table name
func (*UploadFile) TableName() string {
	return TableNameUploadFile
}
