// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUserGood = "user_goods"

// UserGood 用户购买商品表
type UserGood struct {
	ID         int64 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID     int64 `gorm:"column:user_id;not null;comment:用户id" json:"user_id"`         // 用户id
	OrderID    int64 `gorm:"column:order_id;not null;comment:订单id" json:"order_id"`       // 订单id
	GoodsID    int64 `gorm:"column:goods_id;not null;comment:商品id" json:"goods_id"`       // 商品id
	GoodsType  int32 `gorm:"column:goods_type;not null;comment:商品类型" json:"goods_type"`   // 商品类型
	BuyTime    int64 `gorm:"column:buy_time;not null;comment:购买时间" json:"buy_time"`       // 购买时间
	ExpireTime int64 `gorm:"column:expire_time;not null;comment:到期时间" json:"expire_time"` // 到期时间
}

// TableName UserGood's table name
func (*UserGood) TableName() string {
	return TableNameUserGood
}
