// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "user"

// User 用户表
type User struct {
	ID       int64  `gorm:"column:id;primaryKey" json:"id"`
	NickName string `gorm:"column:nick_name;not null" json:"nick_name"`
	/*
		0：男，1：女

	*/
	Sex      int32     `gorm:"column:sex;not null;comment:0：男，1：女\n" json:"sex"`
	Password string    `gorm:"column:password;not null" json:"password"`
	Status   int32     `gorm:"column:status;not null;default:1;comment:1：正常，-1：禁用" json:"status"` // 1：正常，-1：禁用
	Avatar   string    `gorm:"column:avatar;not null;comment:云存储key" json:"avatar"`               // 云存储key
	CreateAt time.Time `gorm:"column:create_at;not null;default:CURRENT_TIMESTAMP" json:"create_at"`
	UpdateAt time.Time `gorm:"column:update_at;not null" json:"update_at"`
	CreateBy int64     `gorm:"column:create_by;not null" json:"create_by"`
	UpdateBy int64     `gorm:"column:update_by;not null" json:"update_by"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
