// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameWechatUser = "wechat_user"

// WechatUser 微信用户表
type WechatUser struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID       int64     `gorm:"column:user_id;not null;comment:用户id" json:"user_id"`                   // 用户id
	WechatUserID int64     `gorm:"column:wechat_user_id;not null;comment:微信用户uuid" json:"wechat_user_id"` // 微信用户uuid
	Avatar       string    `gorm:"column:avatar;not null" json:"avatar"`
	NickName     string    `gorm:"column:nick_name;not null" json:"nick_name"`
	CreateAt     time.Time `gorm:"column:create_at;not null;default:CURRENT_TIMESTAMP" json:"create_at"`
	UpdateAt     time.Time `gorm:"column:update_at;not null" json:"update_at"`
}

// TableName WechatUser's table name
func (*WechatUser) TableName() string {
	return TableNameWechatUser
}
